version: '3'

networks:
    konnex-net:
        driver: bridge

volumes:
    konnex-opcua-volume:

services: 
    things-db:
        image: mysql
        ports: 
            - "3306:3306"
        environment: 
            - MYSQL_ROOT_PASSWORD=konnexthings
            - MYSQL_DATABASE=thingsdb
            - MYSQL_ROOT_HOST=%
        networks: 
            - konnex-net

    konnex-things:
        build: 
            context: .
            dockerfile: ./Dockerfile
            args: 
                SERVICE: things
        ports: 
            - 8080:8080
        depends_on:
            - things-db
        networks: 
            - konnex-net
    
    users-db:
        image: mysql
        ports: 
            - "33061:3306"
        environment: 
            - MYSQL_ROOT_PASSWORD=konnexusers
            - MYSQL_DATABASE=usersdb
            - MYSQL_ROOT_HOST=%
        networks: 
            - konnex-net

    konnex-users:
        build: 
            context: .
            dockerfile: ./Dockerfile
            args: 
                SERVICE: users
        ports: 
            - 8081:8081
            - 9000:9000
        networks: 
            - konnex-net

    konnex-opcua:
        build: 
            context: .
            dockerfile: ./Dockerfile
            args: 
                SERVICE: opcua
        ports: 
            - 8082:8082
        networks: 
            - konnex-net
        volumes:
            - konnex-opcua-volume:/store
    
    konnex-redis:
        image: redis:6.2-alpine
        restart: always
        ports:
            - '6379:6379'
        networks:
            - konnex-net 