version: '3'

networks:
    konnex-net:
        driver: bridge

volumes:
    konnex-opcua-volume:

services:
    nginx:
        image: nginx
        ports:
            - "443:443"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/ssl:/etc/nginx/ssl:ro
            - ./nginx/index.html:/app/html:ro
        networks:
            - konnex-net
        depends_on:
            - konnex-things
            - konnex-users
            - konnex-opcua

    things-db:
        image: mysql
        ports: 
            - "3306:3306"
        environment: 
            - MYSQL_ROOT_PASSWORD=konnexthings
            - MYSQL_DATABASE=thingsdb
            - MYSQL_ROOT_HOST=%
        networks: 
            - konnex-net        

    konnex-things:
        build: 
            context: .
            dockerfile: ./Dockerfile
            args: 
                SERVICE: things
        ports: 
            - 8080:8080
        depends_on:
            - things-db
        networks: 
            - konnex-net
    
    users-db:
        image: mysql
        ports: 
            - "33061:3306"
        environment: 
            - MYSQL_ROOT_PASSWORD=konnexusers
            - MYSQL_DATABASE=usersdb
            - MYSQL_ROOT_HOST=%
        networks: 
            - konnex-net

    konnex-users:
        build: 
            context: .
            dockerfile: ./Dockerfile
            args: 
                SERVICE: users
        ports: 
            - 8081:8081
            - 9000:9000
        networks: 
            - konnex-net

    opcua-db:
        image: timescale/timescaledb:latest-pg11
        environment:
            - POSTGRES_USER=opcua
            - POSTGRES_PASSWORD=konnexopcua
            - POSTGRES_DB=opcua
        ports:
            - "5432:5432"
        networks:
            - konnex-net

    konnex-opcua:
        build: 
            context: .
            dockerfile: ./Dockerfile
            args: 
                SERVICE: opcua
        ports: 
            - 8082:8082
        networks: 
            - konnex-net
        depends_on:
            - opcua-db
        volumes:
            - konnex-opcua-volume:/store
    
    konnex-redis:
        image: redis:6.2-alpine
        restart: always
        ports:
            - '6379:6379'
        networks:
            - konnex-net 